### ISSUE TITLE
Consistently aborts before launch template node detaches from asg

### ISSUE THREAD

**Issue by TBeijen** [hellofresh/eks-rolling-update#22]
I'm currently setting up EKS clusters with worker groups based on launch templates (using terraform-aws-eks).

Gave this tool a spin and so far all attempts aborted when waiting for the first node to detach from the asg.

Now of course it's possible to increase `GLOBAL_MAX_RETRY` and that works, typically at the 16th attempt or so. But it raises some questions:

* Have things become slower on AWS side? Or do asgs based on launch templates behave differently (slower) than based on launch configuration?
* Have you (maintainers) or other people experienced this as well?
* Would it be wise to increase the defaults? Or introduce a separate setting for detach retry?
* What failure scenario does the wait for detach aim to prevent? If I observe what happens during the process while waiting for the detach, I see the EC2 instance has succesfully terminatedand is gone from the cluster. I suppose it's a way of waiting for the asg state to 'settle down' before proceeding on the next node? Would it be possible to already proceed to the next node when observing the terminated node having lifecycle state 'Detaching'?

See below fragment of `aws autoscaling describe-auto-scaling-groups` output. Wouldn't checking for `LifecycleState=Detaching` suffice? It could speed up the rolling update process by a significant amount.

```
   {
        "InstanceId": "i-nnnnnnnnn",
        "AvailabilityZone": "eu-west-1c",
        "LifecycleState": "Detaching",
        "HealthStatus": "Unhealthy",
        "LaunchTemplate": {
            "LaunchTemplateId": "lt-nnnnnnnnnn",
            "LaunchTemplateName": "apps-ng-annnnnnnnn",
            "Version": "2"
        },
        "ProtectedFromScaleIn": false
    }
```

**Comment by chadlwilson** [comment]
In our case the issue seems to be ELB Connection Draining (on an NLB w/NodePort). Default timeout is 5 minutes; which is longer than the default config of this tool (4 minutes).

Haven't yet investigated where the connections are coming from that aren't being drained and/or why; but I wasn't seeing these earlier on a different cluster that was using a classic LB w/LoadBalancer.

**Comment by chadlwilson** [comment]
@crhuber would you & team be open to a PR here for one of the below?
1) only wait for `LifecycleState=Detaching` as suggested by @TBeijen **OR**
2) make waiting for detachment optional

Since the instance is already terminated, I'm also not sure of the value of waiting here.

We use ASG + NLB + Target Group and even with target group deregistration delay being lowered, we see detachment of an individual terminated instance taking anywhere from 60s -> 140s per node which is massively slowing down the tool. Possibly we have some config issue with our instance/LB/target group health checks but would still be nice to have a bit more control over this.

**Comment by crhuber** [comment]
@chadlwilson @TBeijen We havent come across that one, but a PR would be welcome
