### ISSUE TITLE
cordoning node removes the node from loadbalancer causing downtime

### ISSUE THREAD

**Issue by akshaychitneni** [hellofresh/eks-rolling-update#48]
As discussed here https://github.com/kubernetes/kubernetes/issues/65013, while rolling the node pool, cordoning the nodes will remove all the nodes from the loadbalancer which might cause downtime. Instead, we can taint the node to make it non-schedulable instead of cordoning the node. 

Update: this might not cause downtime as the scale up of nodes in the ASG is done before cordoning of the nodes.

**Comment by chadlwilson** [comment]
Are you able to update the description to supply more context about the specific load balancer/health check setup is required to cause this behaviour in an EKS context? 

Personally, in my setup, we don't observe this behaviour while using the tool; but we use external NLBs with basic TCP checks on `NodePort` ingress `Service`s for the ingress so perhaps that is where things differ. Does this require use of `LoadBalancer` `Service`s to cause an issue?

This will help provide more useful feedback on the PR, especially regarding documentation that might indicate to users which strategy is the right one for them to use.

**Comment by akshaychitneni** [comment]
I observed this issue when dealing with ELB as the service controller removes the cordoned nodes from loadbalancer. However, this may not cause downtime as the script scales up ASG before cordoning the nodes and routes to pods are updated on all the new nodes.

**Comment by iterion** [comment]
We experienced this same issue. It's especially acute if you use RUN_MODE=2 and `clusterTrafficPolicy: Local` on your services. You sometimes get lucky since traffic gets routed to all nodes if none of the nodes are available. But, if you have a lot of traffic and you only have _one_ node in service you can saturate that node very quickly.

It's much better to use run modes that only cordon AZ at a time.

The proposed fix seems like a good one though, so I'm for some variant of #49 being merged.

**Comment by crhuber** [comment]
Resolved by https://github.com/hellofresh/eks-rolling-update/pull/49
