### ISSUE TITLE
[Feature] Timeout waiting for instance scale up

### ISSUE THREAD

**Issue by johnthedev97** [hellofresh/eks-rolling-update#55]
Currently, after setting the desired capacity of the ASG, the script simply waits CLUSTER_HEALTH_WAIT seconds once (without any retries) to check if all instances come online. This works in best case scenarios, but we observe good amount of variances in AWS when it comes to time it takes for instances to come online. (In my current example that lead to this issue it took 9 minutes).

I know I can increase the CLUSTER_HEALTH_WAIT to 600s, but that means it always wait 10 minutes which is waste of time. So my request is to add a retry, so that we can have a worst case timeout  without increasing the rollout time in best case scenario.

**Comment by crosbymichael1** [comment]
I have ran into this similar issue many times as well and its definitely frustrating to have to go and edit the tags in the console to be able to rerun the job, or the only reason it failed is because the instances weren't spun up or down before the health check ends. I put a PR in for this @johnthedev97 so hope its able to help you! #58

**Comment by johnthedev97** [comment]
Thank you very much @crosbymichael1, I really appreciate it.

**Comment by crhuber** [comment]
fixed by https://github.com/hellofresh/eks-rolling-update/pull/58
