### ISSUE TITLE
Cluster autoscaler paused - memory issue

### ISSUE THREAD

**Issue by eperdeme** [hellofresh/eks-rolling-update#61]
Hello,

Just wondering if anybody experiences an issue we face often when using this tool.

We run the tool which pause cluster autoscaler and then proceeds to cordon/drain ASGS one at a time. 
We often find we get pods unschedulable on to nodes due to not enough memory, we always set a memory request=limit (java) but as to be expected when pods are evicted in some scenarios they spread over the new nodes in a way that no single node has enough free space to run a large pod.

What if anything could we do to stop this ? One options to not disable autoscaler which the eks-rolling-update docs say is optional to disable, but what negative issues would occur if we did this ?

**Comment by chadlwilson** [comment]
This sounds to me like you might have a cluster/node sizing problem that might be independent of this tool? If you have pods that `request` for large percentages of a node's allocatable memory then you may always have scheduling challenges, even if doing a regular K8s deployment rollout?

Although I haven't tried it, I suspect if you don't pause the cluster autoscaler and a scaling operation happens that the tool might get confused about how many nodes it is expecting to come online due to cause race conditions that could be bad.

Due to the way the tool currently works, it saves snapshots of the ASG sizes into tags at the start, and then when it has moved workloads, then reverts these changes at the end, so then I believe it might then cause the ASG to do an uncontrolled scale down of one of the new nodes that have been created by the autoscaler.

Presumably with the current approach, when the cluster autoscaler is unpaused after `eks-rolling-update` it sees the unschedulable pod(s) and adds a node to handle them. Is your primary concern about efficiency of the whole process, or possibly losing all available replicas to handle traffic as a result of the update?

**Comment by eperdeme** [comment]
I don't believe it to be a sizing problem, as normally autoscaler would add more capacity based on the demand of a deployment.

The problem and you are right it's not this tools problem, is that when the ASG grows from 3->6, on these 3 new nodes pods can be scheduled in such a way that (lots of small pods randomly evicted first) that when a large pod is evicted and then tries to schedule no 1 node has enough free memory, overall there might be 3 nodes each with 2Gb free, but no 1 node has 3Gb free to host the evicted large pod, which then results in PDB blocking eks-rolling-update until autoscaler is re-enabled.

I'm not expecting the tool to be able to solve this, but I was more curious if other users ever have similar issues and did they work around it. We see this problem a lot and normally we have to re-run it several times per cluster and between each run we re-enable autoscaler to increase the capacity.

I've attached a diagram to show the problem that we experience. The memory usage is an example, our nodes are normally 16Gb and a large pod could be 10Gb.

![pod tetris](https://user-images.githubusercontent.com/158550/93470863-73f9ae00-f8ea-11ea-99ad-f184f7dda703.png)

**Comment by chadlwilson** [comment]
Personally I see that somewhat as a sizing problem because it implies that prior to rolling update you are often running nodes that are packed to the brim and with little spare capacity, such that when you double the ASG side there might be highly dependent on the scheduler deciding on basically the same packing/scheduling arrangement as on the source nodes, which is unlikely. With possibly aggressive PDBs which allow little disruption c.f the # of replicas in the deployment that doesn't seem to allow K8s much room to move when evicting larger #s of pods.

I guess if you want more room to move, you might need to allow more resources. If I were currently running pods that use 62.5% of a node's memory in requests, personally I would either be looking at using bigger nodes which can handle more bin-packing variations; using taints and tolerations to ensure my massive pods were on special nodes in a special ASG, or looking at [pod priority/preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) to consider the massive pods higher priority so that the small pods will be evicted to make space for them if necessary during the rolling update if it makes sub-optimal scheduling decisions. The preemption approach definitely still has some risks regarding PDB violations so still need to ensure sufficient "room to move".

As a side note, it does depend on the nature of the Java app, but personally I don't prefer to run Java pods at request==limits or in such a way that a pod can be taking such a large % of a node's memory.

I've also [seen articles about pod priority being used for cluster over-provisioning](https://medium.com/scout24-engineering/cluster-overprovisiong-in-kubernetes-79433cb3ed0e) to workaround cluster-autoscaler weaknesses and insufficient allowance for the required buffer/slack to deal with horizontal pod autoscaling (or in this case temporary mass evictions due to node rolls).

**Comment by eperdeme** [comment]
Cheers. We'll give it a go. Thank you for the tool it's does a good job.
